#' Main Cleaning Function
#'
#' @param path Path to the CVR file or directory
#' @param metadata (optional) Existing metadata to merge into the CVR
#' @param generate_metadata Whether to generate new metadata using a series of rules and then append these to the CVR. Default is `FALSE`.
#' @param return_metadata Return the metadata generated by the function for the user to examine? Default `FALSE`.
#' @param metadata_only Only return the metadata generated, and skip returning the file itself? Useful for getting a blank slate of metadata that users could then manually adjust before returning via the `metadata=` argument. Default `FALSE`.
#' @param verbose Verbose output? Default `FALSE`
#' @param write_path (optional) Path to write a parquet file, in which case the function only returns a path
#'
#' @returns Either a `tibble` with the cleaned CVR (`return_metadata=FALSE`) or a list containing both the cleaned CVR and the generated metadata (`generate_metadata=TRUE` and `return_metadata=FALSE`) or just the generated metadata (`metadata_only=TRUE`) or a path to the output file (`write_dir` is non-NULL).
#' @export
#'
clean_cvr <- function(
  path=NA,
  metadata=NULL,
  generate_metadata=FALSE,
  return_metadata=FALSE,
  metadata_only=FALSE,
  verbose=TRUE,
  write_path=NULL
) {

  if (!is.null(metadata) & isTRUE(generate_metadata)) {
    cli::cli_alert_info("{.var metadata} is non-NULL so {.var generate_metadata} is being ignored")
  }

  path = fs::path_real(path)
  type = classify_cvr(path, verbose=FALSE)

  if (length(type) > 1){
    path = fs::path(path, type[["path"]])
    type = type[["type"]]
  }

  if (verbose) cli::cli_alert_info("Cleaning {.file {path}}")

  fix_fragmentation <- function(raw){

    # is the ballot fragmented across rows?
    if ("ballot_style" %in% colnames(raw)){

      if (dplyr::distinct(raw, ballot_style) |> dplyr::pull() |> stringr::str_detect("\\[\\d+\\]$") |> sum() > 0) {

        cli::cli_warn("{.file {path}} appears to contain fragmented ballots (where the ballot is split across multiple rows). We attempt to repair this by merging rows together using an intelligent strategy, but any further analysis should be taken with caution.")

        base = raw |>
          dplyr::mutate(
            ballot_style2 = stringr::str_remove(ballot_style, " \\[\\d+\\]$")
          ) |>
          dplyr::group_by(ballot_style2) |>
          tidyr::fill(
            tidyselect::everything(),
            .direction = "downup"
          ) |>
          dplyr::ungroup()

        tokeep = base |>
          dplyr::count(ballot_style2, ballot_style, sort=TRUE) |>
          dplyr::filter(n == max(n), .by = ballot_style2) |>
          dplyr::slice_head(n=1, by = ballot_style2) |>
          dplyr::select(ballot_style)

        raw = dplyr::semi_join(base, tokeep, dplyr::join_by("ballot_style"))

      }

    }

    return(raw)

  }

  get_delim <- function(path){

    path = fs::path_real(path)

    if (is_header(path)) {
      raw <- header_processor(path)
    } else {
      ext <- fs::path_ext(path) |> stringr::str_to_upper()

      raw <- switch(ext,
        "CSV" = data.table::fread(path, colClasses = character(), header=TRUE),
        "XLS" = readxl::read_excel(path, col_types = "text", .name_repair = "unique_quiet"),
        "XLSX" = readxl::read_excel(path, col_types = "text", .name_repair = "unique_quiet"),
      )
    }

    colnames(raw) <- iconv(colnames(raw), to = "UTF-8", sub = "")

    # rename some columns with a fuzzy match
    dplyr::rename(raw, tidyselect::any_of(rcvr_RENAME_COLS))

  }
  clean_delim <- function(raw){

    raw = fix_fragmentation(raw)

    d <- raw |>
      # drop all of the unnecessary columns
      dplyr::select(-tidyselect::any_of(rcvr_DROP_COLS)) |>
      # manually define cvr_id as 1:n()
      dplyr::mutate(
        "cvr_id" = 1:dplyr::n()
      ) |>
      tidyr::pivot_longer(
        cols = -tidyselect::any_of(c("state", "county_name", "cvr_id", "precinct")),
        names_to = "contest",
        values_to = "raw_candidate",
        values_drop_na = TRUE
      ) |>
      tidyr::separate_wider_delim(cols = contest, delim = "||", names = c("contest", "candidate", "raw_party"), too_few = "align_start") |>
      # some rows are aggregated values (CvrNumber=`Redacted and Aggregated...`), need to drop these rows
      dplyr::filter(
        suppressWarnings(as.numeric(raw_candidate)) <= 1 | is.na(suppressWarnings(as.numeric(raw_candidate))),
        contest != raw_candidate
      ) |>
      dplyr::filter(raw_candidate != "0", raw_candidate != "") |>
      dplyr::group_by(precinct) |>
      tidyr::complete(
        cvr_id, tidyr::nesting(contest)
      ) |>
      dplyr::ungroup() |>
      # if they voted, then we just use their lookup table candidate choice
      # if they didn't vote, they get assigned to undervote
      # then, we replace all the 0s with NA, now that we've identified undervote
      #
      # this also deals with CVRs that have contests as columns and cands as cells
      dplyr::mutate(
        raw_candidate = dplyr::case_when(
          raw_candidate %in% rcvr_REDACT_NAMES ~ NA_character_,
          is.na(raw_candidate) ~ "undervote",
          .default = dplyr::coalesce(candidate, raw_candidate)
        ),
        candidate = NULL
      )

    if (isTRUE(generate_metadata)) metadata = gen_metadata(d, type, path, verbose)
    if (isTRUE(metadata_only)) return(metadata)

    clean <- d |>
      mutate(
        across(c(contest, raw_candidate, raw_party), ~na_if(.x, ""))
      ) |>
      dplyr::left_join(metadata, dplyr::join_by("contest", "raw_candidate", "raw_party")) |>
      mutate(
        party = dplyr::coalesce(party, raw_party),
      ) |>
      # add metadata for writein/undervote/overvote candidates
      dplyr::group_by(contest) |>
      tidyr::fill(office, district, magnitude, .direction = "downup") |>
      dplyr::ungroup()

    if (isTRUE(return_metadata)) {

      return(
        list(
          clean = clean,
          metadata = metadata
        )
      )

    } else {
      return(clean)
    }


  }

  get_json <- function(path){

    rlang::check_installed("dominionCVR", reason = "`dominionCVR` is needed to parse JSON files")

    files = list.files(path = path, pattern = "Cvr.*\\.json$|CVR.*\\.json$", full.names = TRUE)

    dominionCVR::extract_cvr(files)

  }
  clean_json <- function(raw){

    if (isTRUE(generate_metadata)) metadata = gen_metadata(raw, type, path, verbose)
    if (isTRUE(metadata_only)) return(metadata)

    clean <- raw |>
      dplyr::left_join(metadata, dplyr::join_by("contest", "raw_candidate", "raw_party")) |>
      mutate(
        magnitude = coalesce(magnitude.x, magnitude.y),
        party_detailed = coalesce(party_detailed.x, party_detailed.y),
        candidate = coalesce(candidate.y, candidate.x)
      ) |>
      # this block helps identify undervotes in the 1/0 CVR format
      dplyr::mutate(
        voted = ifelse(
          all(raw_candidate %in% c("0", rcvr_REDACT_NAMES) | stringr::str_detect(raw_candidate, stringr::regex("undervote", ignore_case=TRUE))),
          0,
          1
        ),
        .by = c("cvr_id", "contest")
      ) |>
      # if they voted, then we just use their lookup table candidate choice
      # if they didn't vote, they get assigned to undervote
      # then, we replace all the 0s with NA, now that we've identified undervote
      #
      # this also deals with CVRs that have contests as columns and cands as cells
      dplyr::mutate(
        party = dplyr::coalesce(party, raw_party),
        candidate = dplyr::case_when(
          voted == 0 & raw_candidate %in% rcvr_REDACT_NAMES ~ NA_character_,
          voted == 0 ~ "undervote",
          raw_candidate == "0" ~ NA_character_,
          .default = dplyr::coalesce(candidate, raw_candidate)
        ),
        voted = NULL
      ) |>
      # add metadata for writein/undervote/overvote candidates
      dplyr::group_by(contest) |>
      tidyr::fill(office, district, magnitude, .direction = "downup") |>
      dplyr::ungroup()

    if (isTRUE(return_metadata)) {

      return(
        list(
          clean = clean,
          metadata = metadata
        )
      )

    } else {
      return(clean)
    }


  }

  if (type == "DELIM") {

    clean <- get_delim(path) |> clean_delim()

  }
  else if (type == "DELIM-MULTI") {

    clean <- lapply(list.files(path, recursive=TRUE, full.names=TRUE), get_delim) |>
      dplyr::bind_rows() |>
      clean_delim()

  }
  else if (type == "JSON") {

    clean <- get_json(path) |> clean_json()

  }

  if (!is.null(write_path)) {
    rlang::check_installed("arrow", reason = "`arrow` is needed to write Parquet files")

    fs::dir_create(fs::path_dir(write_path))
    arrow::write_parquet(clean, write_path)
    return(write_path)
  }

  return(clean)

}
