#' Attach store values to a pairs frame
#'
#' A left join, guarded by an anti-join check. A raw pair with no store row is
#' a hard error for that county: it means the store has not been seeded or
#' reconciled for this file, and silently dropping the rows is precisely the
#' failure mode this package exists to remove.
#'
#' Pairs matching `rcvr_UNSEEDED_RE` (undervote, overvote, write-in, `"0"`)
#' are exempt — they are synthesised by the reader and `gen_metadata()`
#' deliberately never seeds them into the store.
#'
#' @param pairs A pairs frame.
#' @param metadata A store slice, already filtered to one
#'   `(election, state, county)`.
#' @param state,county Used only in the error message.
#'
#' @return The pairs frame with store columns attached.
join_metadata <- function(pairs, metadata, state = NA, county = NA) {
  if (is.null(metadata)) {
    cli::cli_abort(
      "{.var metadata} is required unless {.var generate_metadata} or {.var metadata_only} is {.code TRUE}.",
      class = "rcvr_no_metadata"
    )
  }

  # the slice arrives carrying the store key columns; they are constant within
  # a slice and would collide with the caller's own columns downstream.
  # raw_party is dropped too: the pairs frame already carries its own
  # raw_party (the reader's copy, authoritative), and the store's copy is
  # identical by construction, so keeping both would produce
  # raw_party.x/raw_party.y from left_join() below
  meta <- dplyr::select(
    metadata,
    -tidyselect::any_of(c("election", "state", "county", "raw_party"))
  )

  # gen_metadata()'s dplyr::distinct(contest, raw_candidate, raw_party) can
  # emit two store rows sharing (contest, raw_candidate) when a county spells
  # one candidate's party two ways. The left join below then fans a single
  # ballot row out into two, silently inflating vote totals -- so this must
  # be caught before the join runs, not after.
  dupes <- dplyr::filter(
    meta,
    dplyr::n() > 1,
    .by = c(contest, raw_candidate)
  )
  if (nrow(dupes) > 0) {
    shown <- utils::head(dplyr::distinct(dupes, contest, raw_candidate), 10)
    cli::cli_abort(
      c(
        "{nrow(shown)} {.val {'(contest, raw_candidate)'}} pair{?s} in the metadata store {?has/have} more than one row.",
        "x" = paste0(shown$contest, " / ", shown$raw_candidate),
        "i" = "A left join against a duplicated pair fans out ballot rows; reconcile the store for this county before cleaning it."
      ),
      class = "rcvr_duplicate_metadata",
      pairs = dupes
    )
  }

  # an NA raw_candidate is never exempt: str_detect(NA, ...) is NA, and
  # dplyr::filter() drops NA conditions, so without coalescing to FALSE an
  # NA-keyed pair would silently skip the anti-join and survive the left
  # join with every store column NA — exactly the silent loss this
  # function exists to prevent
  joinable <- dplyr::filter(
    pairs,
    !dplyr::coalesce(stringr::str_detect(raw_candidate, rcvr_UNSEEDED_RE), FALSE)
  )

  unmatched <- dplyr::anti_join(
    dplyr::distinct(joinable, contest, raw_candidate),
    meta,
    dplyr::join_by("contest", "raw_candidate")
  )

  if (nrow(unmatched) > 0) {
    shown <- utils::head(unmatched, 10)
    cli::cli_abort(
      c(
        "{nrow(unmatched)} raw pair{?s} in {.val {state}} / {.val {county}} {?has/have} no row in the metadata store.",
        "x" = paste0(shown$contest, " / ", shown$raw_candidate),
        "i" = "Seed and reconcile the store for this county before cleaning it."
      ),
      class = "rcvr_unmatched_pairs",
      pairs = unmatched
    )
  }

  dplyr::left_join(pairs, meta, dplyr::join_by("contest", "raw_candidate")) |>
    # writein/undervote/overvote rows inherit their contest's office metadata
    dplyr::group_by(contest) |>
    tidyr::fill(office, district, magnitude, .direction = "downup") |>
    dplyr::ungroup()
}

#' Main Cleaning Function
#'
#' @param path Path to the CVR file or directory
#' @param type (optional) The declared CVR type from the registry: one of `"delim"`, `"json"`, `"xml"`, `"special"`. When `NULL` (default) the type is sniffed from the files on disk, which aborts on directories holding more than one file type.
#' @param metadata (optional) Existing metadata to merge into the CVR
#' @param generate_metadata Whether to generate new metadata using a series of rules and then append these to the CVR. Default is `FALSE`.
#' @param return_metadata Return the metadata generated by the function for the user to examine? Default `FALSE`.
#' @param metadata_only Only return the metadata generated, and skip returning the file itself? Useful for getting a blank slate of metadata that users could then manually adjust before returning via the `metadata=` argument. Default `FALSE`.
#' @param verbose Verbose output? Default `FALSE`
#' @param write_path (optional) Path to write a parquet file, in which case the function only returns a path
#' @param election The election label, e.g. `"2020 General"`. Required when generating metadata.
#' @param state The state name, upper case. Required when generating metadata.
#' @param county The county name, upper case. Required when generating metadata.
#'
#' @returns Either a `tibble` with the cleaned CVR (`return_metadata=FALSE`) or a list containing both the cleaned CVR and the generated metadata (`generate_metadata=TRUE` and `return_metadata=FALSE`) or just the generated metadata (`metadata_only=TRUE`) or a path to the output file (`write_path` is non-NULL).
#' @export
#'
clean_cvr <- function(
  path=NA,
  type=NULL,
  metadata=NULL,
  generate_metadata=FALSE,
  return_metadata=FALSE,
  metadata_only=FALSE,
  verbose=TRUE,
  write_path=NULL,
  election=NA_character_,
  state=NA_character_,
  county=NA_character_
) {

  if (!is.null(metadata) && isTRUE(generate_metadata)) {
    cli::cli_inform(
      "{.var metadata} is non-NULL so {.var generate_metadata} is being ignored."
    )
    generate_metadata <- FALSE
  }

  if (!checkmate::test_string(path, na.ok = FALSE)) {
    cli::cli_abort(
      "{.arg path} must be a single non-NA string.",
      class = "rcvr_bad_path"
    )
  }

  path <- fs::path_real(path)
  resolved <- resolve_reader(path, type = type, verbose = FALSE)
  path <- resolved$path
  type <- resolved$type

  valid_types <- c("DELIM", "DELIM-MULTI", "JSON", "XML", "SPECIAL")
  if (is.null(type) || !checkmate::test_string(type) || !(type %in% valid_types)) {
    cli::cli_abort(
      "Could not resolve a CVR type for {.file {path}}.",
      class = "rcvr_bad_type"
    )
  }

  if (type == "SPECIAL" && (is.na(state) || is.na(county))) {
    cli::cli_abort(
      "{.var state} and {.var county} are required for {.val special} CVRs.",
      class = "rcvr_missing_county"
    )
  }

  if (verbose) cli::cli_alert_info("Cleaning {.file {path}}")

  if (type == "DELIM") {
    pairs <- read_delim_cvr(path) |> pairs_from_delim(path)
  } else if (type == "DELIM-MULTI") {
    pairs <- read_delim_multi_cvr(path) |> pairs_from_delim(path)
  } else if (type == "JSON") {
    pairs <- read_json_cvr(path)
  } else if (type == "XML") {
    pairs <- read_xml_cvr(path)
  } else if (type == "SPECIAL") {
    pairs <- read_special_cvr(path, state, county)
  }

  if (isTRUE(generate_metadata) || isTRUE(metadata_only)) {
    metadata <- gen_metadata(pairs, type, path, election, state, county, verbose)
  }
  if (isTRUE(metadata_only)) return(metadata)

  clean <- join_metadata(pairs, metadata, state = state, county = county)

  if (isTRUE(return_metadata)) {
    return(list(clean = clean, metadata = metadata))
  }

  if (!is.null(write_path)) {
    rlang::check_installed("arrow", reason = "`arrow` is needed to write Parquet files")

    fs::dir_create(fs::path_dir(write_path))
    arrow::write_parquet(clean, write_path)
    return(write_path)
  }

  return(clean)

}
