#' Main Cleaning Function
#'
#' @param path Path to the CVR file or directory
#' @param type (optional) The declared CVR type from the registry: one of `"delim"`, `"json"`, `"xml"`, `"special"`. When `NULL` (default) the type is sniffed from the files on disk, which aborts on directories holding more than one file type.
#' @param metadata (optional) Existing metadata to merge into the CVR
#' @param generate_metadata Whether to generate new metadata using a series of rules and then append these to the CVR. Default is `FALSE`.
#' @param return_metadata Return the metadata generated by the function for the user to examine? Default `FALSE`.
#' @param metadata_only Only return the metadata generated, and skip returning the file itself? Useful for getting a blank slate of metadata that users could then manually adjust before returning via the `metadata=` argument. Default `FALSE`.
#' @param verbose Verbose output? Default `FALSE`
#' @param write_path (optional) Path to write a parquet file, in which case the function only returns a path
#' @param election The election label, e.g. `"2020 General"`. Required when generating metadata.
#' @param state The state name, upper case. Required when generating metadata.
#' @param county The county name, upper case. Required when generating metadata.
#'
#' @returns Either a `tibble` with the cleaned CVR (`return_metadata=FALSE`) or a list containing both the cleaned CVR and the generated metadata (`generate_metadata=TRUE` and `return_metadata=FALSE`) or just the generated metadata (`metadata_only=TRUE`) or a path to the output file (`write_dir` is non-NULL).
#' @export
#'
clean_cvr <- function(
  path=NA,
  type=NULL,
  metadata=NULL,
  generate_metadata=FALSE,
  return_metadata=FALSE,
  metadata_only=FALSE,
  verbose=TRUE,
  write_path=NULL,
  election=NA_character_,
  state=NA_character_,
  county=NA_character_
) {

  if (!is.null(metadata) & isTRUE(generate_metadata)) {
    cli::cli_alert_info("{.var metadata} is non-NULL so {.var generate_metadata} is being ignored")
  }

  path <- fs::path_real(path)
  resolved <- resolve_reader(path, type = type, verbose = FALSE)
  path <- resolved$path
  type <- resolved$type

  if (verbose) cli::cli_alert_info("Cleaning {.file {path}}")

  if (type == "DELIM") {
    pairs <- read_delim_cvr(path) |> pairs_from_delim(path)
  } else if (type == "DELIM-MULTI") {
    pairs <- read_delim_multi_cvr(path) |> pairs_from_delim(path)
  } else if (type == "JSON") {
    pairs <- read_json_cvr(path)
  } else if (type == "XML") {
    pairs <- read_xml_cvr(path)
  }

  if (isTRUE(generate_metadata) || isTRUE(metadata_only)) {
    metadata <- gen_metadata(pairs, type, path, election, state, county, verbose)
  }
  if (isTRUE(metadata_only)) return(metadata)

  clean <- pairs |>
    dplyr::inner_join(metadata, dplyr::join_by("contest", "raw_candidate")) |>
    dplyr::group_by(contest) |>
    tidyr::fill(office, district, magnitude, .direction = "downup") |>
    dplyr::ungroup()

  if (isTRUE(return_metadata)) {
    return(list(clean = clean, metadata = metadata))
  }

  if (!is.null(write_path)) {
    rlang::check_installed("arrow", reason = "`arrow` is needed to write Parquet files")

    fs::dir_create(fs::path_dir(write_path))
    arrow::write_parquet(clean, write_path)
    return(write_path)
  }

  return(clean)

}
