# unneeded columns to drop from the data
rcvr_DROP_COLS <- c(
  "Cast Vote Record", "RowNumber", "CvrNumber", "CVRNumber", "Cvr Number", "Cast.Vote.Record",
  "BallotID", "Ballot Id", "Dummy Row Number", "Row Number", "Unique Voting Identifier", 
  "Ballot Style", "BallotStyleID", "ballot_style2", "Ballot Style Id", "Ballot.Style", 
  "Ballot Type", "BallotType", "BallotTypeId",
  "Ballot Status", 
  "BoxID", "Box Id", "BoxPosition", "Box Position", 
  "PrecinctStyleName", "PrecinctStyleName (Redacted to Protect Voter Privacy)",
  "CountingGroup", "Counting Group",
  "TabulatorNum", "Tabulator Num", "Tabulator Name", "TabulatorId", 
  "Batch Id", "BatchId", "Batch", 
  "Record Id", "RecordId", 
  "ImprintedId", "Imprinted Id",
  "Image Path", 
  "Session Type", 
  "Voter Flag", 
  "Modified", 
  "Card Info", 
  "Pdf Name", 
  "ScanComputerName", "Scan Computer Name",
  "Status", 
  "Remade",
  "Voting Session Identifier", 
  "Is Current"
)

# appended by `header_processor()` to make duplicate column names unique.
# Chosen so it cannot occur in vendor data and can be stripped unambiguously
# before the name is split back into (contest, candidate, party).
rcvr_DUP_SENTINEL <- "__RCVRDUP__"

# various permutations of a label that the cell is redacted
rcvr_REDACT_NAMES = c("X", "redacted for voter privacy", "REDACTED", "Redacted", "*", "redacted", "Redacted per 24-27-205.5 (4)(b)(III) C.R.S.")

# various permutations of the precinct column name
rcvr_RENAME_COLS <- c(
  ballot_style = "Ballot Style",
  ballot_style = "BallotStyle",
  ballot_style = "BallotStyleID",
  ballot_style = "BallotType",
  precinct = "Precinct Portion",
  precinct = "PrecinctPortionID",
  precinct = "Precinct",
  precinct = "PrecinctID",
  precinct = "Precinct Id",
  precinct = "PrecinctId",
  precinct = "Precinct Portion Id",
  precinct = "PrecinctBySplit",
  precinct = "PrecinctPortionId",
  precinct = "Precinct ID",
  precinct = "precinct_number",
  precinct = "PRECINCT CODE",
  precinct = "PRECINCT NAME",
  precinct = "PrecinctPortion",
  precinct = "PrecinctStyleName"
)

#' Check if delimited file has an unconventional header
#'
#' @param path the path to the delimited file
#'
#' @return boolean
is_header <- function(path) {

  # get the top-left cell's contents
  if (stringr::str_detect(path, "csv$|CSV$")) {
    rlang::check_installed("data.table", reason = "to read CSV files")
    d <- data.table::fread(path, nrows=1, select=1, header=FALSE)[[1]]
  } else if (stringr::str_detect(path, "xls$|xlsx$|XLS$|XLSX$")) {
    rlang::check_installed("readxl", reason = "to read Excel files")
    d <- readxl::read_excel(path, range = "A1", col_names = FALSE, .name_repair = "unique_quiet") |> dplyr::pull()
  }

  # if we detect the top left column to include something like this, it's almost certainly
  # a header file. There may be a more systematic way to check for headers but this
  # works without fail on every file in the data
  stringr::str_detect(d, stringr::regex("202|General|November", ignore_case = TRUE))
}

#' Process delimited files with unconventional headers. They are
#' generated by one of the voting machine vendors, and include
#' the name of the election in the top left, then a blank line, then
#' three rows of information on each column. Sometimes the order of the rows varies
#' but they always include the contest, the name of the candidate, and their party.
#' In addition, the first m columns are metadata columns related to the CVR. This
#' function processes these files into a more regular delimited format, with a singular
#' row for the header. There is also an edge case in some counties (e.g., San Diego, CA 2020)
#' wherein the header is inexplicably repeated partway through the file. The chunk that
#' generates `bad_rows` removes this extra information.
#'
#' @param path The path to the file
#' @param n The number of rows to read. This is used to generate the raw contests
#' quickly, without reading the entire file.
#'
#' @return A tibble formatted with conventional headers
header_processor <- function(path, n = Inf) {

  checkmate::assertCharacter(path)
  checkmate::assert_number(n, lower=1)

  if (stringr::str_detect(path, "csv$|CSV$")) {
    rlang::check_installed("data.table", reason = "to read CSV files")
    df <- data.table::fread(
      path,
      skip=1,
      nrows=n,
      header=TRUE,
      # `character()` (a zero-length vector) is a no-op for `colClasses`, which
      # let fread's type inference silently turn all-numeric-looking metadata
      # columns (e.g. a Precinct column of "001"/"002") into integers,
      # dropping the leading zero. The pairs-frame contract requires
      # character; force it here as done in `read_delim_cvr()`.
      colClasses="character"
    )

  } else if (stringr::str_detect(path, "xls$|xlsx$|XLS$|XLSX$")) {
    rlang::check_installed("readxl", reason = "to read Excel files")

    df <- readxl::read_excel(
      path,
      skip=1,
      n_max=n,
      .name_repair = "unique_quiet",
      col_names = TRUE,
      col_types = "text",
    )
  }

  ncols = ncol(df)

  # sometimes these header files have repeated rows in the middle that need to be removed
  bad_rows = which(df[ncols-1] == colnames(df)[ncols-1] |> stringr::str_remove("\\.\\.\\.\\d+")) |>
    purrr::map(~ (.x - 1):(.x + 2)) |>
    unlist()

  colnames(df) = paste(colnames(df), df[1, ], df[2, ], sep = "||") |>
    stringr::str_remove("\\.\\.\\.\\d+") |>
    stringr::str_remove_all("^NA\\|\\||\\|\\|NA|^\\|\\|") |>
    stringr::str_remove_all("\\|\\|NA|^\\|\\|") |>
    iconv(to = "UTF-8", sub = "") |>
    stringr::str_remove_all("^V\\d+") |>
    stringr::str_remove_all("^\\|\\|") |>
    stringr::str_remove_all("^\\|\\|") |>
    # a metadata column (e.g. CvrNumber, Precinct) with blank candidate/party
    # header cells pastes as e.g. "CvrNumber||||"; fread reads a blank cell as
    # "" (not NA) once colClasses forces character, so the "||NA" removals
    # above don't catch it. A key column must never carry this artefact, so
    # strip trailing empty "||" components here too.
    stringr::str_remove_all("(\\|\\|)+$") |>
    make.unique(sep = rcvr_DUP_SENTINEL)

  df[-c(bad_rows, 1, 2), ]

}

# Pairs the metadata store never seeds a row for. gen_metadata() drops
# undervote/overvote/write-in/"0"/redacted from the seed after cleaning
# raw_candidate via seed_candidate(), so join_metadata()'s anti-join check
# must exempt the same raw pairs or it would abort a county on perfectly good
# ballots (a write-in vote, an overvote, a redacted cell). One regex serves
# both call sites so they cannot drift: "undervote"/"overvote"/"0" are
# spelled identically raw and cleaned; "Write" is the same substring test
# seed_candidate() uses to collapse a raw write-in spelling to the cleaned
# "WI"; and the literal "WI" is included so gen_metadata()'s post-seed filter
# (which tests the already-cleaned `candidate` column) keeps its exact prior
# behaviour. "redacted" is the literal sentinel pairs_from_delim() maps every
# rcvr_REDACT_NAMES spelling to (R/read_delim.R), so a redacted cell never
# has to survive as an NA raw_candidate, which join_metadata() would coalesce
# to non-exempt and abort on.
rcvr_UNSEEDED_RE <- stringr::regex("^undervote$|^overvote$|^WI$|^0$|^redacted$|Write", ignore_case = TRUE)

# the column contract every reader must satisfy
rcvr_PAIRS_COLS <- c(
  cvr_id = "integer",
  precinct = "character",
  contest = "character",
  raw_candidate = "character",
  raw_party = "character",
  rank = "integer"
)

#' Assert that a reader returned a valid pairs frame
#'
#' @param pairs A tibble returned by one of the `read_*_cvr()` readers.
#' @param call The calling environment, for error reporting.
#'
#' @return `pairs`, invisibly. Aborts with class `rcvr_bad_pairs` otherwise.
assert_pairs <- function(pairs, call = rlang::caller_env()) {
  # all(is.na(x)) is vacuously TRUE for a length-0 vector, so every type
  # check below is satisfied by an empty frame. A reader whose filters
  # removed every row would otherwise return a zero-row "success",
  # indistinguishable from a clean_cvr() run that silently lost a whole
  # county.
  if (nrow(pairs) == 0) {
    cli::cli_abort(
      "Pairs frame has zero rows.",
      class = "rcvr_bad_pairs",
      call = call
    )
  }

  missing <- setdiff(names(rcvr_PAIRS_COLS), colnames(pairs))
  if (length(missing) > 0) {
    cli::cli_abort(
      "Pairs frame is missing required column{?s}: {.field {missing}}",
      class = "rcvr_bad_pairs",
      call = call
    )
  }

  actual <- vapply(pairs[names(rcvr_PAIRS_COLS)], typeof, character(1))
  expected <- unname(rcvr_PAIRS_COLS)
  # R stores integers as "integer" and characters as "character"; logical NA
  # columns are tolerated only when the column is entirely NA
  bad <- names(rcvr_PAIRS_COLS)[
    actual != expected & !vapply(pairs[names(rcvr_PAIRS_COLS)], function(x) all(is.na(x)), logical(1))
  ]
  if (length(bad) > 0) {
    cli::cli_abort(
      c(
        "Pairs frame column{?s} {.field {bad}} {?has/have} the wrong type.",
        "i" = "Expected {.val {unname(rcvr_PAIRS_COLS[bad])}}, got {.val {unname(actual[bad])}}."
      ),
      class = "rcvr_bad_pairs",
      call = call
    )
  }

  invisible(pairs)
}
