# unneeded columns to drop from the data
rcvr_DROP_COLS <- c(
  "Cast Vote Record", "Ballot Style", "RowNumber",
  "BoxID", "BoxPosition", "BallotID", "BallotStyleID",
  "PrecinctStyleName", "ScanComputerName", "Status", "Remade",
  "PrecinctStyleName (Redacted to Protect Voter Privacy)",
  "CvrNumber", "TabulatorNum", "Batch Id", "Record Id",
  "ImprintedId", "BallotType", "CountingGroup", "Precinct Portion",
  "Dummy Row Number", "Row Number", "Image Path", "Session Type", "Cast.Vote.Record",
  "Ballot.Style", "Voter Flag", "Modified", "Card Info", "Pdf Name", "Unique Voting Identifier",
  "Voting Session Identifier", "CVRNumber", "BallotTypeId",
  "TabulatorId", "BatchId", "RecordId", "Tabulator Name", "Is Current",
  "Box Id", "Box Position", "Ballot Id", "Ballot Style Id", "Scan Computer Name",
  "ballot_style", "ballot_style2", "Batch", "Ballot Status"
)

# various permutations of a label that the cell is redacted
rcvr_REDACT_NAMES = c("X", "redacted for voter privacy", "REDACTED", "Redacted", "*", "redacted")

# various permutations of the precinct column name
rcvr_RENAME_COLS <- c(
  ballot_style = "Ballot Style",
  ballot_style = "BallotStyle",
  precinct = "Precinct Portion",
  precinct = "PrecinctPortionID",
  precinct = "Precinct",
  precinct = "PrecinctID",
  precinct = "Precinct Id",
  precinct = "PrecinctId",
  precinct = "Precinct Portion Id",
  precinct = "PrecinctBySplit",
  precinct = "PrecinctPortionId",
  precinct = "Precinct ID",
  precinct = "precinct_number",
  precinct = "PRECINCT CODE",
  precinct = "PRECINCT NAME",
  precinct = "PrecinctPortion"
)

#' Check if delimited file has an unconventional header
#'
#' @param path the path to the delimited file
#'
#' @return boolean
is_header <- function(path) {

  # get the top-left cell's contents
  if (stringr::str_detect(path, "csv$|CSV$")) {
    rlang::check_installed("data.table", reason = "to read CSV files")
    d <- data.table::fread(path, nrows=1, select=1)[[1]]
  } else if (stringr::str_detect(path, "xls$|xlsx$|XLS$|XLSX$")) {
    rlang::check_installed("readxl", reason = "to read Excel files")
    d <- readxl::read_excel(path, range = "A1", col_names = FALSE, .name_repair = "unique_quiet") |> dplyr::pull()
  }

  # if we detect the top left column to include something like this, it's almost certainly
  # a header file. There may be a more systematic way to check for headers but this
  # works without fail on every file in the data
  stringr::str_detect(d, stringr::regex("202|General|November", ignore_case = TRUE))
}

#' Process delimited files with unconventional headers. They are
#' generated by one of the voting machine vendors, and include
#' the name of the election in the top left, then a blank line, then
#' three rows of information on each column. Sometimes the order of the rows varies
#' but they always include the contest, the name of the candidate, and their party.
#' In addition, the first m columns are metadata columns related to the CVR. This
#' function processes these files into a more regular delimited format, with a singular
#' row for the header. There is also an edge case in some counties (e.g., San Diego, CA 2020)
#' wherein the header is inexplicably repeated partway through the file. The chunk that
#' generates `bad_rows` removes this extra information.
#'
#' @param path The path to the file
#' @param n The number of rows to read. This is used to generate the raw contests
#' quickly, without reading the entire file.
#'
#' @return A tibble formatted with conventional headers
header_processor <- function(path, n = Inf) {

  checkmate::assertCharacter(path)
  checkmate::assert_number(n, lower=1)

  if (stringr::str_detect(path, "csv$|CSV$")) {
    rlang::check_installed("data.table", reason = "to read CSV files")
    df <- data.table::fread(
      path,
      skip=1,
      nrows=n,
      header=TRUE,
      colClasses=character()
    )

  } else if (stringr::str_detect(path, "xls$|xlsx$|XLS$|XLSX$")) {
    rlang::check_installed("readxl", reason = "to read Excel files")

    df <- readxl::read_excel(
      path,
      skip=1,
      n_max=n,
      .name_repair = "unique_quiet",
      col_names = TRUE,
      col_types = "text",
    )
  }

  ncols = ncol(df)

  # sometimes these header files have repeated rows in the middle that need to be removed
  bad_rows = which(df[ncols-1] == colnames(df)[ncols-1] |> stringr::str_remove("\\.\\.\\.\\d+")) |>
    purrr::map(~ (.x - 1):(.x + 2)) |>
    unlist()

  colnames(df) = paste(colnames(df), df[1, ], df[2, ], sep = "||") |>
    stringr::str_remove("\\.\\.\\.\\d+") |>
    stringr::str_remove_all("^NA\\|\\||\\|\\|NA|^\\|\\|") |>
    stringr::str_remove_all("\\|\\|NA|^\\|\\|") |>
    iconv(to = "UTF-8", sub = "") |>
    stringr::str_remove_all("^V\\d+") |>
    stringr::str_remove_all("^\\|\\|") |>
    stringr::str_remove_all("^\\|\\|")

  df[-c(bad_rows, 1, 2), ]

}
